language: node_js

node_js:
   - '10.16.0'

branches:
 only:
  - master
  
before_script:
  - sudo npm install -g ionic cordova

script:
  - ionic cordova build browser
  - ionic cordova run browser
 
deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN 
 keep-history: true
 on:
    branch: master
 local_dir: www